### ISSUE TITLE
Suspicious dead-code compiler warning

### ISSUE THREAD

**Issue by raquo** [sherpal/url-dsl#15]
I noticed a scala 3 compiler warning in [language/Fragment.scala](https://github.com/sherpal/url-dsl/blob/f8d9f98d2728ade5fcff2463178eca73c046c7f2/url-dsl/src/main/scala/urldsl/language/Fragment.scala#L175-L178):

```
[warn] -- [E030] Match case Unreachable Warning: /Users/raquo/code/scala/url-dsl/url-dsl/src/main/scala/urldsl/language/Fragment.scala:178:15
[warn] 178 |          case Right(value) => Left(fragmentMatchingError.wrongValue(value, t))
[warn]     |               ^^^^^^^^^^^^
[warn]     |               Unreachable case
```

From

```
implicit def asFragment[T, A](t: T)(
      implicit fromString: FromString[T, A],
      printer: Printer[T],
      fragmentMatchingError: FragmentMatchingError[A],
      classTag: ClassTag[T]
  ): Fragment[Unit, A] =
        ...
        fromString(fragment) match {
          case Left(value)  => Left(value)
          case Right(_: T)  => Right(())
          case Right(value) => Left(fragmentMatchingError.wrongValue(value, t))
        }
```

To my eye, the code looks fine thanks to `ClassTag[T]`, yet here we are.

At the very least we should add a test case to exercise the `Right(value)` case. However, I'm not sure under what circumstances `fromString` can produce a Right of something other than `T`.

**Comment by sherpal** [comment]
Yes I saw them once and I was very surprised that it would cause this warning.
I will have a look because I think it shouldn't happen. Making a test for that seems like a plan :+1:

**Comment by sherpal** [comment]
It turns out the compiler is right, we never go to the last branch. I am curious why it was even there in the first place.

However, that unveiled a stupid bug, I don't even check that the decoded value is equal to the provided `t` 😱 

I will try to setup scoverage to (try to) shed some light into missing tests...
