### ISSUE TITLE
Support fragment # in url

### ISSUE THREAD

**Issue by ngbinh** [sherpal/url-dsl#2]
Many SPA rely on the use of fragment `#` to allow changing pages without a browser reload. Would be great if `url-dsl` support that.

Thanks

**Comment by sherpal** [comment]
Indeed, this needs to be supported.

In the spirit of the `&`, `/` and `?` methods, and given Scala's restrictions on the `#` symbol, what would you think of using the `###` symbol for that? Or perhaps you would prefer a named method (like `withFragment`?).

Also, how would like a url ending by `stuff#` to behave? In particular, would you consider the fragment to be absent, or to be the empty string? Fun fact: the Java api returns null in that case whereas the JavaScript API returns the empty string, hence my question. I would consider the fragment to be absent.

I really need to find time for this.

**Comment by ngbinh** [comment]
I think `withFragment` should be fine. I think you can treat `stuff#` the same as `stuff` as long as it is stated clearly. 

Thanks

**Comment by sherpal** [comment]
It took me a while, because I decided to unify and clean a certain number of things on the way, but it's now done.
Still need to ship it to maven central.
